// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/ai/[id]/index.tsx";
import * as $2 from "./routes/ai/[id]/worker.tsx";
import * as $3 from "./routes/ai/index.tsx";
import * as $4 from "./routes/ai/post.tsx";
import * as $5 from "./routes/battle.tsx";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/Battle.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/ai/[id]/index.tsx": $1,
    "./routes/ai/[id]/worker.tsx": $2,
    "./routes/ai/index.tsx": $3,
    "./routes/ai/post.tsx": $4,
    "./routes/battle.tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/Battle.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
